### ISSUE TITLE
Array Index Out Of Bounds Exception: Index 2048 out of bounds for length 1025

### ISSUE THREAD

**Issue by manmaed** [VazkiiMods/AutoRegLib#82] opened 2022-08-11 10:49 UTC
**Log Files**
latest.log: https://pastebin.com/WT4A0Vyr
debug.log: Unable to paste due to suze
Crash Report: https://pastebin.com/0EWM59D9

**Steps to reproduce**
Unkown!

**Expected behaviour**
Not To Crash

**Screenshots**
![](https://ss.manmaed.net/1660214043.png)

**Comment by Saereth** [comment] 2022-09-13 19:11
if it helps, EvilCraft was having a similar issue and he moved his color registration to ColorHandlerEvent.item as opposed to the FMLLoadCompleteEvent event and it did resolve the error. His change commit is here if its helpful. Although there isnt perfect code parity with your registrations here I suspect the root cause is similar.

https://github.com/CyclopsMC/EvilCraft/commit/6aa5952802a0c712f388413fd0d06ed10338b01d

This happens maybe 1/10 launches. Enough to be a concern for a pack releasing but not terribly reproducible on demand

**Comment by Gurtygurt98** [comment] 2022-10-28 00:32
Playing on the newest version of FTB Plexiglass and get this exact error frequently, past 5 launches have resulted in this error 
[crash-2022-10-27_20.29.19-fml.txt](https://github.com/VazkiiMods/AutoRegLib/files/9883838/crash-2022-10-27_20.29.19-fml.txt)
[crash-2022-10-27_20.24.08-fml.txt](https://github.com/VazkiiMods/AutoRegLib/files/9883839/crash-2022-10-27_20.24.08-fml.txt)
[crash-2022-10-27_20.11.48-fml.txt](https://github.com/VazkiiMods/AutoRegLib/files/9883841/crash-2022-10-27_20.11.48-fml.txt)
[crash-2022-10-27_18.18.33-fml.txt](https://github.com/VazkiiMods/AutoRegLib/files/9883842/crash-2022-10-27_18.18.33-fml.txt)
[crash-2022-10-27_18.15.05-fml.txt](https://github.com/VazkiiMods/AutoRegLib/files/9883843/crash-2022-10-27_18.15.05-fml.txt)

**Comment by unilock** [comment] 2023-02-06 14:47
This was fixed in 1.19, but not 1.18:
["Register color handlers using the forge event" - eed6bc4](https://github.com/VazkiiMods/AutoRegLib/commit/eed6bc48d0b569b8f389a37153ceca93726f8950)

So I backported it:
https://github.com/unilock/AutoRegLib/tree/1.18-ColorHandlerEvent

([release](https://github.com/unilock/AutoRegLib/releases/tag/v1.7.1-54))

**Closed** 2024-11-05 01:43 UTC
